language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
script:
  - npm run lint:test:cover
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
